from .display import (
    create_blank_ax,
    create_map_ax,
    create_side_by_side_ax,
    create_3d_ax,
    display_objective_over_iterations,
    display_routing_grid,
    create_aco_animation,
    display_flight_path,
    display_flight_altitude,
    display_flight_path_3d,
    create_3d_flight_animation,
    display_geodesic_path,
    display_flight_ef,
    show,
)
